Testsuite: gov.nasa.jpf.test.vm.basic.ExceptionHandlingTest
Tests run: 9, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 7.575 sec
------------- Standard Output ---------------
  running jpf with args:
JavaPathfinder core system v8.0 (rev 32+) - (C) 2005-2014 United States Government. All rights reserved.


====================================================== system under test
gov.nasa.jpf.test.vm.basic.ExceptionHandlingTest.runTestMethod()

====================================================== search started: 9/7/17 11:30 AM

====================================================== error 1
gov.nasa.jpf.vm.NoUncaughtExceptionsProperty
java.lang.NullPointerException: referencing field 'data' on null object
	at gov.nasa.jpf.test.vm.basic.ExceptionHandlingTest.testNPE(ExceptionHandlingTest.java:44)
	at java.lang.reflect.Method.invoke(gov.nasa.jpf.vm.JPF_java_lang_reflect_Method)
	at gov.nasa.jpf.util.test.TestJPF.runTestMethod(TestJPF.java:648)


====================================================== snapshot #1
thread java.lang.Thread:{id:0,name:main,status:RUNNING,priority:5,isDaemon:false,lockCount:0,suspendCount:0}
  call stack:
	at gov.nasa.jpf.util.test.TestJPF.runTestMethod(TestJPF.java:650)


====================================================== results
error #1: gov.nasa.jpf.vm.NoUncaughtExceptionsProperty "java.lang.NullPointerException: referencing field ..."

====================================================== search finished: 9/7/17 11:30 AM
  running jpf with args:
JavaPathfinder core system v8.0 (rev 32+) - (C) 2005-2014 United States Government. All rights reserved.


====================================================== system under test
gov.nasa.jpf.test.vm.basic.ExceptionHandlingTest.runTestMethod()

====================================================== search started: 9/7/17 11:30 AM

====================================================== error 1
gov.nasa.jpf.vm.NoUncaughtExceptionsProperty
java.lang.ArrayIndexOutOfBoundsException: 10
	at gov.nasa.jpf.test.vm.basic.ExceptionHandlingTest.testArrayIndexOutOfBoundsHigh(ExceptionHandlingTest.java:71)
	at java.lang.reflect.Method.invoke(gov.nasa.jpf.vm.JPF_java_lang_reflect_Method)
	at gov.nasa.jpf.util.test.TestJPF.runTestMethod(TestJPF.java:648)


====================================================== snapshot #1
thread java.lang.Thread:{id:0,name:main,status:RUNNING,priority:5,isDaemon:false,lockCount:0,suspendCount:0}
  call stack:
	at gov.nasa.jpf.util.test.TestJPF.runTestMethod(TestJPF.java:650)


====================================================== results
error #1: gov.nasa.jpf.vm.NoUncaughtExceptionsProperty "java.lang.ArrayIndexOutOfBoundsException: 10  at g..."

====================================================== search finished: 9/7/17 11:30 AM
  running jpf with args:
JavaPathfinder core system v8.0 (rev 32+) - (C) 2005-2014 United States Government. All rights reserved.


====================================================== system under test
gov.nasa.jpf.test.vm.basic.ExceptionHandlingTest.runTestMethod()

====================================================== search started: 9/7/17 11:30 AM

====================================================== results
no errors detected

====================================================== search finished: 9/7/17 11:30 AM
  running jpf with args:
JavaPathfinder core system v8.0 (rev 32+) - (C) 2005-2014 United States Government. All rights reserved.


====================================================== system under test
gov.nasa.jpf.test.vm.basic.ExceptionHandlingTest.runTestMethod()

====================================================== search started: 9/7/17 11:30 AM

====================================================== error 1
gov.nasa.jpf.vm.NoUncaughtExceptionsProperty
java.lang.ArrayIndexOutOfBoundsException: -1
	at gov.nasa.jpf.test.vm.basic.ExceptionHandlingTest.testArrayIndexOutOfBoundsLow(ExceptionHandlingTest.java:62)
	at java.lang.reflect.Method.invoke(gov.nasa.jpf.vm.JPF_java_lang_reflect_Method)
	at gov.nasa.jpf.util.test.TestJPF.runTestMethod(TestJPF.java:648)


====================================================== snapshot #1
thread java.lang.Thread:{id:0,name:main,status:RUNNING,priority:5,isDaemon:false,lockCount:0,suspendCount:0}
  call stack:
	at gov.nasa.jpf.util.test.TestJPF.runTestMethod(TestJPF.java:650)


====================================================== results
error #1: gov.nasa.jpf.vm.NoUncaughtExceptionsProperty "java.lang.ArrayIndexOutOfBoundsException: -1  at g..."

====================================================== search finished: 9/7/17 11:30 AM
  running jpf with args:
JavaPathfinder core system v8.0 (rev 32+) - (C) 2005-2014 United States Government. All rights reserved.


====================================================== system under test
gov.nasa.jpf.test.vm.basic.ExceptionHandlingTest.runTestMethod()

====================================================== search started: 9/7/17 11:30 AM

====================================================== results
no errors detected

====================================================== search finished: 9/7/17 11:30 AM
  running jpf with args:
JavaPathfinder core system v8.0 (rev 32+) - (C) 2005-2014 United States Government. All rights reserved.


====================================================== system under test
gov.nasa.jpf.test.vm.basic.ExceptionHandlingTest.runTestMethod()

====================================================== search started: 9/7/17 11:30 AM

====================================================== error 1
gov.nasa.jpf.vm.NoUncaughtExceptionsProperty
java.lang.NullPointerException: Calling 'foo()V' on null object
	at gov.nasa.jpf.test.vm.basic.ExceptionHandlingTest.testNPECall(ExceptionHandlingTest.java:53)
	at java.lang.reflect.Method.invoke(gov.nasa.jpf.vm.JPF_java_lang_reflect_Method)
	at gov.nasa.jpf.util.test.TestJPF.runTestMethod(TestJPF.java:648)


====================================================== snapshot #1
thread java.lang.Thread:{id:0,name:main,status:RUNNING,priority:5,isDaemon:false,lockCount:0,suspendCount:0}
  call stack:
	at gov.nasa.jpf.util.test.TestJPF.runTestMethod(TestJPF.java:650)


====================================================== results
error #1: gov.nasa.jpf.vm.NoUncaughtExceptionsProperty "java.lang.NullPointerException: Calling 'foo()V' o..."

====================================================== search finished: 9/7/17 11:30 AM
  running jpf with args:
JavaPathfinder core system v8.0 (rev 32+) - (C) 2005-2014 United States Government. All rights reserved.


====================================================== system under test
gov.nasa.jpf.test.vm.basic.ExceptionHandlingTest.runTestMethod()

====================================================== search started: 9/7/17 11:30 AM

====================================================== results
no errors detected

====================================================== search finished: 9/7/17 11:30 AM
  running jpf with args:
JavaPathfinder core system v8.0 (rev 32+) - (C) 2005-2014 United States Government. All rights reserved.


====================================================== system under test
gov.nasa.jpf.test.vm.basic.ExceptionHandlingTest.runTestMethod()

====================================================== search started: 9/7/17 11:30 AM
	 at gov.nasa.jpf.test.vm.basic.ExceptionHandlingTest.testStackTrace(gov/nasa/jpf/test/vm/basic/ExceptionHandlingTest.java:129)
	 at java.lang.reflect.Method.invoke(gov.nasa.jpf.vm.JPF_java_lang_reflect_Method:-1)
	 at gov.nasa.jpf.util.test.TestJPF.runTestMethod(gov/nasa/jpf/util/test/TestJPF.java:648)

====================================================== results
no errors detected

====================================================== search finished: 9/7/17 11:30 AM
  running jpf with args:
JavaPathfinder core system v8.0 (rev 32+) - (C) 2005-2014 United States Government. All rights reserved.


====================================================== system under test
gov.nasa.jpf.test.vm.basic.ExceptionHandlingTest.runTestMethod()

====================================================== search started: 9/7/17 11:30 AM

====================================================== results
no errors detected

====================================================== search finished: 9/7/17 11:30 AM
------------- ---------------- ---------------

Testcase: testNPE took 3.356 sec
Testcase: testArrayIndexOutOfBoundsHigh took 0.685 sec
Testcase: testCallerHandler took 0.736 sec
Testcase: testArrayIndexOutOfBoundsLow took 0.448 sec
Testcase: testLocalHandler took 0.422 sec
Testcase: testNPECall took 0.656 sec
Testcase: testEmptyTryBlock took 0.348 sec
Testcase: testStackTrace took 0.383 sec
Testcase: testEmptyHandler took 0.375 sec
